#! /bin/bash

echo "DIGCOLL_RETRIEVER_VERBOSITY: ${DIGCOLL_RETRIEVER_VERBOSITY:-default}"
echo "DIGCOLL_RETRIEVER_HOST: ${DIGCOLL_RETRIEVER_HOST:-default}"
echo "DIGCOLL_RETRIEVER_PORT: ${DIGCOLL_RETRIEVER_PORT:-default}"
echo "DIGCOLL_RETRIEVER_WORKERS: ${DIGCOLL_RETRIEVER_WORKERS:-default}"
echo "DIGCOLL_RETRIEVER_TIMEOUT: ${DIGCOLL_RETRIEVER_TIMEOUT:-default}"
echo "DIGCOLL_RETRIEVER_MVOL_OWNCLOUD_ROOT: ${DIGCOLL_RETRIEVER_MVOL_OWNCLOUD_ROOT:-omitted}"
echo "DIGCOLL_RETRIEVER_MVOL_OWNCLOUD_USER: ${DIGCOLL_RETRIEVER_MVOL_OWNCLOUD_USER:-omitted}"
echo "DIGCOLL_RETRIEVER_MVOL_OWNCLOUD_SUBPATH: ${DIGCOLL_RETRIEVER_MVOL_OWNCLOUD_SUBPATH:-omitted}"

gunicorn digcollretriever:app -w ${DIGCOLL_RETRIEVER_WORKERS:-4} -t ${DIGCOLL_RETRIEVER_TIMEOUT:-30} -b ${DIGCOLL_RETRIEVER_HOST:-0.0.0.0}:${DIGCOLL_RETRIEVER_PORT:-5000}
